name: Deploy Documentation

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-docs.txt

    - name: Build documentation
      working-directory: ./backend
      run: |
        mkdocs build --strict --verbose

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: backend/site/

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./backend/site
        cname: docs.ccm.example.com  # Optional: your custom domain

  check-docstrings:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install tools
      run: |
        pip install pydocstyle interrogate

    - name: Check docstring coverage
      working-directory: ./backend
      run: |
        # Check docstring style
        pydocstyle src/ --config=.pydocstyle || true

        # Check docstring coverage
        interrogate -v src/ \
          --fail-under 70 \
          --exclude "*/test_*.py" \
          --generate-badge docs/badges/

    - name: Upload coverage badge
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: docstring-coverage-badge
        path: backend/docs/badges/